/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Green_LED.h
**     Project     : EKG_Dongle
**     Processor   : MK22FN512VLH12
**     Component   : LED
**     Version     : Component 01.075, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-12-05, 17:29, # CodeGen: 27
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : Green_LED
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**            High Value means ON                          : no
**          Shell                                          : Disabled
**     Contents    :
**         On         - void Green_LED_On(void);
**         Off        - void Green_LED_Off(void);
**         Neg        - void Green_LED_Neg(void);
**         Get        - uint8_t Green_LED_Get(void);
**         Put        - void Green_LED_Put(uint8_t val);
**         SetRatio16 - void Green_LED_SetRatio16(uint16_t ratio);
**         Deinit     - void Green_LED_Deinit(void);
**         Init       - void Green_LED_Init(void);
**
**Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**All Rights Reserved.
**
**Redistribution and use in source and binary forms, with or without modification,
**are permitted provided that the following conditions are met:
**
**o Redistributions of source code must retain the above copyright notice, this list
**  of conditions and the following disclaimer.
**
**o Redistributions in binary form must reproduce the above copyright notice, this
**  list of conditions and the following disclaimer in the documentation and/or
**  other materials provided with the distribution.
**
**o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**  contributors may be used to endorse or promote products derived from this
**  software without specific prior written permission.
**
**THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**http: www.freescale.com
**mail: support@freescale.com
** ###################################################################*/
/*!
** @file Green_LED.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup Green_LED_module Green_LED module documentation
**  @{
*/         

#ifndef __Green_LED_H
#define __Green_LED_H

/* MODULE Green_LED. */
#include "MCUC1.h" /* SDK and API used */
#include "Green_LEDconfig.h" /* configuration */

/* Include inherited components */
#include "MCUC1.h"
#include "LEDpin1.h"

#define Green_LED_ClrVal()    LEDpin1_ClrVal() /* put the pin on low level */
#define Green_LED_SetVal()    LEDpin1_SetVal() /* put the pin on high level */
#define Green_LED_SetInput()  LEDpin1_SetInput() /* use the pin as input pin */
#define Green_LED_SetOutput() LEDpin1_SetOutput() /* use the pin as output pin */

#define Green_LED_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define Green_LED_On() LEDpin1_ClrVal()
/*
** ===================================================================
**     Method      :  Green_LED_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Green_LED_Off() LEDpin1_SetVal()
/*
** ===================================================================
**     Method      :  Green_LED_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Green_LED_Neg() LEDpin1_NegVal()
/*
** ===================================================================
**     Method      :  Green_LED_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Green_LED_Get() (!(LEDpin1_GetVal()))
/*
** ===================================================================
**     Method      :  Green_LED_Get (component LED)
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

void Green_LED_Init(void);
/*
** ===================================================================
**     Method      :  Green_LED_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Green_LED_Put(val)  ((val) ? Green_LED_On() : Green_LED_Off())
/*
** ===================================================================
**     Method      :  Green_LED_Put (component LED)
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void Green_LED_Deinit(void);
/*
** ===================================================================
**     Method      :  Green_LED_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void Green_LED_SetRatio16(uint16_t ratio);
/*
** ===================================================================
**     Method      :  Green_LED_SetRatio16 (component LED)
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END Green_LED. */

#endif
/* ifndef __Green_LED_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
